version: '3.8'

services:
  backend:
    build:
      context: ./cunigranja/cunigranja
      dockerfile: Dockerfile
    ports:
      - "5001:80" # Ajusta si tu app escucha en otro puerto
    networks:
      - app-network

  frontend:
    build:
      context: ./frontEndcunigranja
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge