version: '3.8'

services:
  backend:
    build:
      context: ./Backend/cunigranja
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend/cunigranja
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
